{
 "title": "Agave Indexing",
 "tags": [
  "agave",
  "indexing"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node",
    "query": "SELECT \"name\" FROM (SELECT LAST(value) FROM \"validator_name\" GROUP BY \"name\") ORDER BY time DESC"
   },
   {
    "name": "node",
    "label": "Validator ID",
    "query": "SELECT \"host_id\" FROM (SELECT LAST(value) FROM \"validator_name\" WHERE \"name\" =~ /^$node_name$/ GROUP BY \"host_id\") ORDER BY time DESC LIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Available %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "memory-stats",
     "select": [
      [
       { "params": [ "avail_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "memory-stats",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "memory-stats",
     "select": [
      [
       { "params": [ "cached_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Cached" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "memory-stats",
     "select": [
      [
       { "params": [ "buffers_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Buffers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "memory-stats",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Update Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db_store_timings",
     "select": [
      [
       { "params": [ "update_index" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Account Lookup Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "bank-accounts_lt_hash",
     "select": [
      [
       { "params": [ "inspect_account_lookup_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Lookup" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "AccountsDB Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_cache_size",
     "select": [
      [
       { "params": [ "total_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Cache" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "estimate_mem_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Index" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "bank-accounts_lt_hash",
     "select": [
      [
       { "params": [ "num_cache_misses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "RocksDB Block Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cf_name" ], "type": "tag" }
     ],
     "measurement": "blockstore_rocksdb_cfs",
     "select": [
      [
       { "params": [ "block_cache_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "RocksDB Memtables + Table Readers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cf_name" ], "type": "tag" }
     ],
     "measurement": "blockstore_rocksdb_cfs",
     "select": [
      [
       { "params": [ "size_all_mem_tables" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cf_name" ], "type": "tag" }
     ],
     "measurement": "blockstore_rocksdb_cfs",
     "select": [
      [
       { "params": [ "estimate_table_readers_mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Index Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "disk_index_index_file_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Index Files" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "disk_index_data_file_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Data Files Size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "disk_index_data_file_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Data Files Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Accounts Index Entry Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "count_in_mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "In Memory" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Flush: Age Progression Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "ms_per_age" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Flush: Evictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "flush_entries_evicted_from_mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Evicted" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "failed_to_evict" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Failed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "AccountsDB Active Operations (blocking cache flush)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db_active",
     "select": [
      [
       { "params": [ "flush" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Flush" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db_active",
     "select": [
      [
       { "params": [ "clean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Clean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db_active",
     "select": [
      [
       { "params": [ "shrink" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Shrink" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db_active",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Hash" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Index Flush: Disk Index Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index",
     "select": [
      [
       { "params": [ "load_disk_found_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk Reads" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Flush: Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db-flush_accounts_cache",
     "select": [
      [
       { "params": [ "num_accounts_flushed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Accounts Flushed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db-flush_accounts_cache",
     "select": [
      [
       { "params": [ "num_cleaned_roots_flushed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Roots Flushed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Read-Only Accounts Cache (400MB limit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db_store_timings",
     "select": [
      [
       {
        "params": [
         "read_only_accounts_cache_data_size"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Shrink Candidate Selection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shrink_candidate_slots",
     "select": [
      [
       { "params": [ "candidates_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Candidates" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shrink_candidate_slots",
     "select": [
      [
       { "params": [ "selected_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Selected" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "shrink_candidate_slots",
     "select": [
      [
       { "params": [ "deferred_to_next_round_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Deferred" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Append Vecs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index_roots_len",
     "select": [
      [
       { "params": [ "append_vecs_open" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Open" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index_roots_len",
     "select": [
      [
       { "params": [ "append_vecs_open_as_file_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "File I/O" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index_roots_len",
     "select": [
      [
       { "params": [ "append_vecs_dirty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Dirty (need flush)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_index_roots_len",
     "select": [
      [
       { "params": [ "append_vecs_open_as_mmap" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "mmap'd" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Clean Accounts: Timing Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "clean_accounts",
     "select": [
      [
       { "params": [ "construct_candidates_us" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Construct Candidates" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "clean_accounts",
     "select": [
      [
       { "params": [ "accounts_scan" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Accounts Scan" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "clean_accounts",
     "select": [
      [
       { "params": [ "calc_deps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Calc Deps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "clean_accounts",
     "select": [
      [
       { "params": [ "reclaims" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Reclaims" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Flush: Slot Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db-flush_accounts_cache",
     "select": [
      [
       {
        "params": [
         "unflushable_unrooted_slot_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Unflushable Slots" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db-flush_accounts_cache",
     "select": [
      [
       { "params": [ "excess_slot_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Excess Slots (can flush)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Clean Accounts: Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "clean_accounts",
     "select": [
      [
       { "params": [ "useful_keys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Keys Cleaned" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "clean_accounts",
     "select": [
      [
       { "params": [ "total_keys_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Candidates" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "clean_accounts",
     "select": [
      [
       { "params": [ "slots_cleaned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Slots Cleaned" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Flush: Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "accounts_db-flush_accounts_cache",
     "select": [
      [
       { "params": [ "account_bytes_flushed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Flushed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host_id", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  }
 ]
}