name: Tests

on:
  pull_request:
    branches: '*'
  push:
    branches: '*'

jobs:
  test:
    name: "Run basic test suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: "Install Python"
        uses: cerc-io/setup-python@v4
        with:
          python-version: '3.8'
      - name: "Print Python version"
        run: python3 --version
      - name: "Install shiv"
        run: pip install shiv
      - name: "Build local shiv package"
        run: ./scripts/build_shiv_package.sh
      - name: "Run smoke tests"
        run: ./tests/smoke-test/run-smoke-test.sh
