name: Mobymask Demo Build

on:
  pull_request:
    branches: '*'
  push:
    branches:
      - ci-test
      - dboreham/mobymask-v3-demo-test
    paths-ignore:
      - '.gitea/workflows/triggers/*'

jobs:
  test:
    name: "Run mobymask-v3-demo test suite"
    runs-on: ubuntu-latest-arm
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      # At present the stock setup-python action fails on Linux/aarch64
      # Conditional steps below workaroud this by using deadsnakes for that case only
      - name: "Install Python for ARM on Linux"
        if: ${{ runner.arch == 'arm64' && runner.os == 'Linux' }}
        uses: deadsnakes/action@v3.0.1
        with:
          python-version: '3.8'
      - name: "Install Python cases other than ARM on Linux"
        if: ${{ ! (runner.arch == 'arm64' && runner.os == 'Linux') }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: "Print Python version"
        run: python3 --version
      - name: "Install shiv"
        run: pip install shiv
      - name: "Generate build version file"
        run: ./scripts/create_build_tag_file.sh
      - name: "Build local shiv package"
        run: ./scripts/build_shiv_package.sh
      - name: "Run mobymask v3 tests"
        run: ./tests/mobymask-v3-demo/run-test.sh
