{
 "title": "REPLACE_WITH_WATCHER_NAME watcher",
 "tags": [
  "REPLACE_WITH_WATCHER_CHAIN",
  "REPLACE_WITH_WATCHER_JOB"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latest indexed block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_status_block_number{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", kind=\"latest_indexed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream chain head",
   "type": "stat",
   "description": "Chain head block number of the upstream endpoint",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_upstream_block_number{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External chain head",
   "type": "stat",
   "description": "Chain head from an external public endpoint",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_block_number{job=\"chain_heads\", chain=\"REPLACE_WITH_WATCHER_CHAIN\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last block process duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "last_block_process_duration_seconds{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Watcher kind",
   "type": "stat",
   "gridPos": { "h": 2.5, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"server\", field=\"is_active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "diff_upstream",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_upstream_block_number{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sync_status_block_number{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", kind=\"latest_indexed\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "diff_external",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_block_number{job=\"chain_heads\", chain=\"REPLACE_WITH_WATCHER_CHAIN\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sync_status_block_number{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", kind=\"latest_indexed\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "description": "Watcher sync status block numbers",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_processed_block_number{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\"}",
     "legendFormat": "latest_processed"
    },
    {
     "expr": "sync_status_block_number{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", kind=\"latest_canonical\"}",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "sync_status_block_number{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", kind=\"intial_indexed\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Watcher sync mode",
   "type": "stat",
   "gridPos": { "h": 2.5, "w": 4, "x": 0, "y": 5.5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "is_syncing_historical_blocks{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of events in the last block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "last_block_num_events_total{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "DB indexed count ",
   "type": "stat",
   "description": "Total number of entries in the block_progress and event table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_progress_total{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\"}",
     "legendFormat": "block_progress"
    },
    {
     "expr": "event_total{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\"}",
     "legendFormat": "event"
    }
   ]
  },
  {
   "title": "DB size (MB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_size_bytes{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", type=\"watcher\"} / 1024 / 1024",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "database_size_bytes{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", type=\"job-queue\"} / 1024 / 1024",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Num block-processing jobs",
   "type": "timeseries",
   "description": "Total number of pgboss jobs in the db",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "pgboss_jobs_total{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", state=~\"active|retry|failed|cancelled|expired\", name=\"block-processing\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Num event-processing jobs",
   "type": "timeseries",
   "description": "Total number of pgboss jobs in the db",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "pgboss_jobs_total{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", state=~\"active|retry|failed|cancelled|expired\", name=\"event-processing\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Watcher config (upstream eth server)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"upstream\", field=\"is_using_rpc_client\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"upstream\", field=\"is_fevm\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"server\", field=\"rpc_supports_block_hash\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"upstream\", field=\"filter_logs_by_addresses\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"upstream\", field=\"filter_logs_by_topics\"}",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Watcher config (server)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"server\", field=\"is_subgraph_watcher\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"server\", field=\"max_events_block_range\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"server\", field=\"clear_entities_cache_interval\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"server\", field=\"max_simultaneous_requests\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"server\", field=\"max_request_queue_limit\"}",
     "legendFormat": "{{field}}"
    }
   ]
  },
  {
   "title": "Watcher config (job queue)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"jobqueue\", field=\"num_events_in_batch\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"jobqueue\", field=\"block_delay_seconds\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"jobqueue\", field=\"use_block_ranges\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"jobqueue\", field=\"historical_logs_block_range\"}",
     "legendFormat": "{{field}}"
    },
    {
     "expr": "watcher_config_info{job=\"REPLACE_WITH_WATCHER_JOB\", instance=\"REPLACE_WITH_WATCHER_NAME\", category=\"jobqueue\", field=\"historical_max_fetch_ahead\"}",
     "legendFormat": "{{field}}"
    }
   ]
  }
 ]
}