{
 "title": "cerc-io overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "fixturenet-eth-geth-1,fixturenet-eth-geth-2"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "nginx Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"keycloak-nginx-prometheus-exporter:9113\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipld-eth-server Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ipld_eth_server_http_count{instance=\"ipld-eth-server:8090\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "geth API Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(rpc_duration_eth_call_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_call"
    },
    {
     "expr": "rate(rpc_duration_eth_getBlockByHash_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getBlocksByHash"
    },
    {
     "expr": "rate(rpc_duration_eth_getBlockByNumber_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getBlocksByNumber"
    },
    {
     "expr": "rate(rpc_duration_eth_getStorageAt_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "getStorageAt"
    },
    {
     "expr": "rate(rpc_duration_statediff_writeStateDiffAt_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "statediff_writeStateDiffAt"
    },
    {
     "expr": "rate(rpc_duration_eth_chainId_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_chainId"
    },
    {
     "expr": "rate(rpc_duration_statediff_writeStateDiffFor_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "statediff_writeStateDiffFor"
    }
   ]
  },
  {
   "title": "Keycloak Logins/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(keycloak_logins{instance=\"keycloak:8080\"}[90s]) * 60",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Block Positions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{instance=\"${node}:6060\"}",
     "legendFormat": "geth"
    },
    {
     "expr": "statediff_service_last_statediff_height{instance=\"${node}:6060\"}",
     "legendFormat": "statediff"
    }
   ]
  },
  {
   "title": "Block Distance (geth to statediff)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "clamp_min(chain_head_block{instance=\"${node}:6060\"} - on() statediff_service_last_statediff_height{instance=\"${node}:6060\"}, 0)",
     "legendFormat": "Distance"
    }
   ]
  },
  {
   "title": "Statediff Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(statediff_service_succeeded{instance=\"${node}:6060\"}[1m])",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "increase(statediff_service_failed{instance=\"${node}:6060\"}[1m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "statediff_service_underway{instance=\"${node}:6060\"}",
     "legendFormat": "Underway"
    }
   ]
  },
  {
   "title": "Statediff Duty Cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(statediff_service_total_processing_time{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statediff API Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(statediff_service_api_requests{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}