services:
  doublezerod:
    restart: unless-stopped
    image: laconicnetwork/doublezero:local
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      DOUBLEZERO_RPC_ENDPOINT: ${DOUBLEZERO_RPC_ENDPOINT:-http://127.0.0.1:8899}
      DOUBLEZERO_ENV: ${DOUBLEZERO_ENV:-mainnet-beta}
      DOUBLEZERO_EXTRA_ARGS: ${DOUBLEZERO_EXTRA_ARGS:-}
    volumes:
      - doublezero-validator-identity:/data/config:ro
      - doublezero-config:/root/.config/doublezero

volumes:
  doublezero-validator-identity:
  doublezero-config:
