version: "3.2"
services:
  ipld-eth-beacon-db:
    restart: always
    image: cerc/ipld-eth-beacon-db:local
    environment:
      POSTGRES_USER: vdbm
      POSTGRES_DB: cerc_testing
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "nc", "-v", "localhost", "5432"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 3s
    ports:
      - "127.0.0.1:8076:5432"
  ipld-eth-beacon-indexer:
    restart: unless-stopped
    depends_on:
      ipld-eth-beacon-db:
        condition: service_healthy
      fixturenet-eth-lighthouse-1:
        condition: service_healthy
    image: cerc/ipld-eth-beacon-indexer:local
    env_file:
      - ../config/ipld-eth-beacon/indexer.env
