version: '3.2'

services:

  erc721-watcher-db:
    restart: unless-stopped
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=vdbm
      - POSTGRES_MULTIPLE_DATABASES=erc721-watcher,erc721-watcher-job-queue
      - POSTGRES_EXTENSION=erc721-watcher-job-queue:pgcrypto
      - POSTGRES_PASSWORD=password
    volumes:
      - ../config/postgresql/multiple-postgressql-databases.sh:/docker-entrypoint-initdb.d/multiple-postgressql-databases.sh
      - erc721_watcher_db_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:15434:5432"
    healthcheck:
      test: ["CMD", "nc", "-v", "localhost", "5432"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 10s

  erc721-watcher:
    restart: unless-stopped
    depends_on:
      ipld-eth-server:
        condition: service_healthy
      erc721-watcher-db:
        condition: service_healthy
    image: cerc/watcher-erc721:local
    environment:
      - ETH_RPC_URL=http://go-ethereum:8545
    command: ["sh", "-c", "yarn server"]
    volumes:
      - ../config/watcher-erc721/erc721-watcher.toml:/app/packages/erc721-watcher/environments/local.toml
    ports:
      - "0.0.0.0:3009:3009"
      - "0.0.0.0:9003:9001"
    healthcheck:
      test: ["CMD", "nc", "-v", "localhost", "3009"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 5s

volumes:
  erc721_watcher_db_data:
