{
 "title": "Azimuth Watchers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "azimuth-watcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest processed block number",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_processed_block_number{job=\"azimuth\", instance=\"azimuth\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last block process duration (sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "last_block_process_duration_seconds{job=\"azimuth\", instance=\"azimuth\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Database size (MBs)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "database_size_bytes{job=\"azimuth\", instance=\"azimuth\", type=\"watcher\"} / 1024 / 1024",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "database_size_bytes{job=\"azimuth\", instance=\"azimuth\", type=\"job-queue\"} / 1024 / 1024",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total events",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "event_total{job=\"azimuth\", instance=\"azimuth\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ecliptic-watcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest processed block number",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_processed_block_number{job=\"azimuth\", instance=\"ecliptic\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last block process duration (sec)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "last_block_process_duration_seconds{job=\"azimuth\", instance=\"ecliptic\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Database size (MBs)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "database_size_bytes{job=\"azimuth\", instance=\"ecliptic\", type=\"watcher\"} / 1024 / 1024",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "database_size_bytes{job=\"azimuth\", instance=\"ecliptic\", type=\"job-queue\"} / 1024 / 1024",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total events",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "event_total{job=\"azimuth\", instance=\"ecliptic\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}