{
 "title": "Laconicd",
 "tags": [ "registry" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "latest_block_height",
   "type": "stat",
   "description": "The consensus latest block height",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"^(tendermint|cometbft)_consensus_latest_block_height$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tx_count",
   "type": "timeseries",
   "description": "Total number of txs processed via DeliverTx",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tx_count", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "tx_gas_used",
   "type": "timeseries",
   "description": "Total amount of gas used by the last tx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "tx_gas_used", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "tx_successful",
   "type": "timeseries",
   "description": "Total number of successful txs processed via DeliverTx",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "tx_successful", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "tx_gas_wanted",
   "type": "timeseries",
   "description": "Total amount of gas requested by a tx",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "tx_gas_wanted", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "tx_failed",
   "type": "timeseries",
   "description": "Total number of failed txs processed via DeliverTx",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "tx_failed", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "mempool_size",
   "type": "timeseries",
   "description": "Size of the mempool (number of uncommitted transactions)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\"^(tendermint|cometbft)_mempool_size\"}",
     "legendFormat": "mempool_size"
    }
   ]
  },
  {
   "title": "query_count",
   "type": "timeseries",
   "description": "Total query count",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "query_count", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "bond_query_count",
   "type": "timeseries",
   "description": "Bond module query count",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{__name__ =~ \"^_(vulcanize|cerc)_bond_(v1beta1|v1).*_count$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "auction_query_count",
   "type": "timeseries",
   "description": "Auction module query count",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "{__name__ =~ \"^_(vulcanize|cerc)_auction_(v1beta1|v1).*_count$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "registry_query_count",
   "type": "timeseries",
   "description": "Registry module query count",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "{__name__ =~ \"^_(vulcanize|cerc)_registry_(v1beta1|v1).*_count$\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}