{
 "title": "Graph Node Subgraphs",
 "tags": [
  "graph-node",
  "subgraph"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "subgraph_name",
    "label": "Subgraph Name",
    "query": "SELECT name\nFROM subgraphs.subgraph\nWHERE current_version IS NOT NULL;"
   },
   {
    "name": "subgraph_hash",
    "label": "Subgraph Deployment",
    "query": "SELECT deployment\nFROM subgraphs.subgraph_version\n  JOIN subgraphs.subgraph ON subgraph.current_version = subgraph_version.id\nWHERE subgraph.name = '$subgraph_name';"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest indexed block",
   "type": "stat",
   "description": "Head block number for a deployment",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_head{deployment=~\"$subgraph_hash\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream head",
   "type": "stat",
   "description": "Upstream head from graph-node ETH RPC endpoint",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_block_number{job=\"chain_heads\", chain=\"filecoin\", instance=\"graph-node\", exported_chain=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External head (filecoin)",
   "type": "stat",
   "description": "Chain head from an external public endpoint",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_block_number{job=\"chain_heads\", chain=\"filecoin\", instance=\"external\", exported_chain=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH RPC Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deployment_eth_rpc_request_duration{deployment=\"$subgraph_hash\"}",
     "legendFormat": "{{method}}, {{provider}}"
    }
   ]
  },
  {
   "title": "Graph Node Head",
   "type": "stat",
   "description": "Block number of the most recent block synced from Ethereum",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ethereum_chain_head_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "diff_upstream",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_head{deployment=~\"$subgraph_hash\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "latest_block_number{job=\"chain_heads\", chain=\"filecoin\", instance=\"graph-node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "diff_external",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_head{deployment=~\"$subgraph_hash\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "latest_block_number{job=\"chain_heads\", chain=\"filecoin\", instance=\"external\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Chain Cache Latest",
   "type": "stat",
   "description": "Block number of the latest block currently present in the chain head cache",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_cache_latest_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deployment Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_failed{deployment=~\"$subgraph_hash\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "diff_node",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_head{deployment=~\"$subgraph_hash\"}",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "ethereum_chain_head_number", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Block Processing Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deployment_block_processing_duration_sum{deployment=\"$subgraph_hash\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "ETH RPC successful requests rate",
   "type": "timeseries",
   "description": "Rate of successful ETH RPC requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(endpoint_request{conn_type=~\"rpc\", result=~\"success\"}[$__rate_interval])",
     "legendFormat": "{{provider}}, {{req_type}}"
    }
   ]
  },
  {
   "title": "ETH RPC failed requests rate",
   "type": "timeseries",
   "description": "Rate of failed ETH RPC requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(endpoint_request{conn_type=~\"rpc\", result=~\"failure\"}[$__rate_interval])",
     "legendFormat": "{{provider}}, {{req_type}}"
    }
   ]
  }
 ]
}