{
 "title": "sushiswap watcher",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latest processed block number",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_processed_block_number{job=\"sushiswap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last block process duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "last_block_process_duration_seconds{job=\"sushiswap\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Database size (MBs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_size_bytes{job=\"sushiswap\", type=\"watcher\"} / 1024 / 1024",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "database_size_bytes{job=\"sushiswap\", type=\"job-queue\"} / 1024 / 1024",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_total{job=\"sushiswap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}