{
 "title": "Watchers",
 "tags": [ "watcher" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(watcher_config_info,job)"
    }
   },
   {
    "name": "watcher",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   },
   {
    "name": "target_chain",
    "query": {
     "query": "label_values({instance=~\"$watcher\"},chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$watcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "watcher",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "max(watcher_info{job=\"$job\", instance=\"$watcher\"}) by (repository, version, commitHash)"
      }
     ]
    },
    {
     "title": "Last block process duration (s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "last_block_process_duration_seconds{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Latest indexed block",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sync_status_block_number{job=~\"$job\", instance=~\"$watcher\", kind=\"latest_indexed\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upstream head",
     "type": "stat",
     "description": "Chain head block number of the upstream endpoint",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "latest_upstream_block_number{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "External head ($target_chain)",
     "type": "stat",
     "description": "Chain head from an external public endpoint",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "latest_block_number{job=\"chain_heads\", chain=\"$target_chain\", instance=\"external\", exported_chain=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Watcher kind",
     "type": "stat",
     "gridPos": { "h": 2.5, "w": 4, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"server\", field=\"is_active\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "diff_upstream",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "latest_upstream_block_number{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "sync_status_block_number{job=~\"$job\", instance=~\"$watcher\", kind=\"latest_indexed\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "diff_external",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "latest_block_number{job=\"chain_heads\", chain=\"$target_chain\", instance=\"external\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "sync_status_block_number{job=~\"$job\", instance=~\"$watcher\", kind=\"latest_indexed\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of events in the last block",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "last_block_num_events_total{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Sync status",
     "type": "stat",
     "description": "Watcher sync status block numbers",
     "gridPos": { "h": 3, "w": 8, "x": 4, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_processed_block_number{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "latest_processed"
      },
      {
       "expr": "sync_status_block_number{job=~\"$job\", instance=~\"$watcher\", kind=\"latest_canonical\"}",
       "legendFormat": "{{kind}}"
      },
      {
       "expr": "sync_status_block_number{job=~\"$job\", instance=~\"$watcher\", kind=\"intial_indexed\"}",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Watcher sync mode",
     "type": "stat",
     "gridPos": { "h": 2.5, "w": 4, "x": 0, "y": 9.5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "is_syncing_historical_blocks{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB indexed count ",
     "type": "stat",
     "description": "Total number of entries in the block_progress and event table",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "block_progress_total{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "block_progress"
      },
      {
       "expr": "event_total{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "event"
      }
     ]
    },
    {
     "title": "DB size (MB)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "database_size_bytes{job=~\"$job\", instance=~\"$watcher\", type=\"watcher\"} / 1024 / 1024",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "database_size_bytes{job=~\"$job\", instance=~\"$watcher\", type=\"job-queue\"} / 1024 / 1024",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "diff",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "latest_upstream_block_number{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "sync_status_block_number{job=~\"$job\", instance=~\"$watcher\", kind=\"latest_indexed\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "latest_block_number{job=\"chain_heads\", chain=\"$target_chain\", instance=\"external\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Num block-processing jobs",
     "type": "timeseries",
     "description": "Total number of pgboss jobs in the db",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "pgboss_jobs_total{job=~\"$job\", instance=~\"$watcher\", state=~\"active|retry|failed|cancelled|expired\", name=\"block-processing\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Num event-processing jobs",
     "type": "timeseries",
     "description": "Total number of pgboss jobs in the db",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "pgboss_jobs_total{job=~\"$job\", instance=~\"$watcher\", state=~\"active|retry|failed|cancelled|expired\", name=\"event-processing\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "ETH RPC request failures",
     "type": "timeseries",
     "description": "Total number of failed ETH RPC requests by method and provider endpoint ",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "watcher_eth_rpc_errors{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{method}}, {{provider}}"
      }
     ]
    },
    {
     "title": "ETH RPC request durations",
     "type": "timeseries",
     "description": "Time taken by last ETH RPC requests by method and provider endpoint",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "watcher_eth_rpc_request_duration{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{method}}, {{provider}}"
      }
     ]
    },
    {
     "title": "Total ETH RPC request failures (across all watchers)",
     "type": "timeseries",
     "description": "Total number of failed ETH RPC requests by method and provider endpoint  (across all watchers)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum by (method, provider) (watcher_eth_rpc_errors{chain=\"$target_chain\"})",
       "legendFormat": "{{method}}, {{provider}}"
      }
     ]
    },
    {
     "title": "Configured upstream endpoints",
     "type": "table",
     "description": "Configured upstream ETH RPC endpoints",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "watcher_config_upstream_endpoints{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total GQL query count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "gql_query_count_total{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "GQL query count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "targets": [
      {
       "expr": "gql_query_count{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "GQL queries duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gql_query_duration_seconds{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Watcher config (upstream eth server)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"upstream\", field=\"is_using_rpc_client\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"upstream\", field=\"is_fevm\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"server\", field=\"rpc_supports_block_hash\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"upstream\", field=\"filter_logs_by_addresses\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"upstream\", field=\"filter_logs_by_topics\"}",
       "legendFormat": "{{field}}"
      }
     ]
    },
    {
     "title": "Watcher config (server)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"server\", field=\"is_subgraph_watcher\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"server\", field=\"max_events_block_range\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"server\", field=\"clear_entities_cache_interval\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"server\", field=\"max_simultaneous_requests\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"server\", field=\"max_request_queue_limit\"}",
       "legendFormat": "{{field}}"
      }
     ]
    },
    {
     "title": "Watcher config (job queue)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"jobqueue\", field=\"num_events_in_batch\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"jobqueue\", field=\"block_delay_seconds\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"jobqueue\", field=\"use_block_ranges\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"jobqueue\", field=\"historical_logs_block_range\"}",
       "legendFormat": "{{field}}"
      },
      {
       "expr": "watcher_config_info{job=~\"$job\", instance=~\"$watcher\", category=\"jobqueue\", field=\"historical_max_fetch_ahead\"}",
       "legendFormat": "{{field}}"
      }
     ]
    },
    {
     "title": "Num subgraph entities loaded",
     "type": "timeseries",
     "description": "Total number of subgraph entities loaded in event processing",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "event_processing_load_entity_total{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Num subgraph entities cache hits",
     "type": "timeseries",
     "description": "Total number of cache hits for subgraph entites in event processing ",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "targets": [
      {
       "expr": "event_processing_load_entity_cache_hit_total{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Num subgraph entities cached (pruned region)",
     "type": "timeseries",
     "description": "Total number of subgraph entities currently present in pruned region of cache",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "targets": [
      {
       "expr": "cached_pruned_entities_total{job=~\"$job\", instance=~\"$watcher\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  }
 ]
}