{
 "title": "claims watcher",
 "tags": [
  "ethereum",
  "azimuth"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latest indexed block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_status_block_number{job=\"azimuth\", instance=\"claims\", kind=\"latest_indexed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream chain head",
   "type": "stat",
   "description": "Chain head block number of upstream endpoint",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "External chain head",
   "type": "stat",
   "description": "Chain head from a public endpoint (etherscan)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "Last block process duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "last_block_process_duration_seconds{job=\"azimuth\", instance=\"claims\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "description": "Watcher sync status block numbers",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_processed_block_number{job=\"azimuth\", instance=\"claims\"}",
     "legendFormat": "latest_processed"
    },
    {
     "expr": "sync_status_block_number{job=\"azimuth\", instance=\"claims\", kind=\"latest_canonical\"}",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "sync_status_block_number{job=\"azimuth\", instance=\"claims\", kind=\"intial_indexed\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Number of events in the last block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "last_block_num_events_total{job=\"azimuth\", instance=\"claims\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "DB indexed count ",
   "type": "stat",
   "description": "Total number of entries in the block_progress and event table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_progress_total{job=\"azimuth\", instance=\"claims\"}",
     "legendFormat": "block_progress"
    },
    {
     "expr": "event_total{job=\"azimuth\", instance=\"claims\"}",
     "legendFormat": "event"
    }
   ]
  },
  {
   "title": "DB size (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_size_bytes{job=\"azimuth\", instance=\"claims\", type=\"watcher\"} / 1024 / 1024",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "database_size_bytes{job=\"azimuth\", instance=\"claims\", type=\"job-queue\"} / 1024 / 1024",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Num block-processing jobs",
   "type": "timeseries",
   "description": "Total number of pgboss jobs in the db",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "pgboss_jobs_total{job=\"azimuth\", instance=\"claims\", state=~\"active|retry|failed|cancelled|expired\", name=\"block-processing\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Num event-processing jobs",
   "type": "timeseries",
   "description": "Total number of pgboss jobs in the db",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "pgboss_jobs_total{job=\"azimuth\", instance=\"claims\", state=~\"active|retry|failed|cancelled|expired\", name=\"event-processing\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}