FROM cerc/webapp-base:local as builder

ARG CERC_BUILD_TOOL
ARG CERC_BUILD_OUTPUT_DIR

WORKDIR /app
COPY . .
RUN rm -rf node_modules build dist .next*
RUN /scripts/build-app.sh /app /data

FROM cerc/webapp-base:local
COPY --from=builder /data /data
