{
 "title": "cerc-io overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "fixturenet-eth-geth-1,fixturenet-eth-geth-2"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "nginx Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{instance=\"keycloak-nginx-prometheus-exporter:9113\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ipld-eth-server Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ipld_eth_server_http_count{instance=\"ipld-eth-server:8090\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "geth API Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(rpc_duration_eth_blockNumber_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_blockNumber"
    },
    {
     "expr": "rate(rpc_duration_eth_call_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_call"
    },
    {
     "expr": "rate(rpc_duration_eth_chainId_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_chainId"
    },
    {
     "expr": "rate(rpc_duration_eth_estimateGas_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_estimateGas"
    },
    {
     "expr": "rate(rpc_duration_eth_gasPrice_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_gasPrice"
    },
    {
     "expr": "rate(rpc_duration_eth_getBalance_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getBalance"
    },
    {
     "expr": "rate(rpc_duration_eth_getBlockByHash_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getBlockByHash"
    },
    {
     "expr": "rate(rpc_duration_eth_getBlockByNumber_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getBlockByNumber"
    },
    {
     "expr": "rate(rpc_duration_eth_getBlockReceipts_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getBlockReceipts"
    },
    {
     "expr": "rate(rpc_duration_eth_getBlockTransactionCountByHash_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getBlockTransactionCountByHash"
    },
    {
     "expr": "rate(rpc_duration_eth_getBlockTransactionCountByNumber_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getBlockTransactionCountByNumber"
    },
    {
     "expr": "rate(rpc_duration_eth_getCode_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getCode"
    },
    {
     "expr": "rate(rpc_duration_eth_getFilterChanges_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getFilterChanges"
    },
    {
     "expr": "rate(rpc_duration_eth_getFilterLogs_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getFilterLogs"
    },
    {
     "expr": "rate(rpc_duration_eth_getLogs_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getLogs"
    },
    {
     "expr": "rate(rpc_duration_eth_getStorageAt_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getStorageAt"
    },
    {
     "expr": "rate(rpc_duration_eth_getTransactionByBlockHashAndIndex_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getTransactionByBlockHashAndIndex"
    },
    {
     "expr": "rate(rpc_duration_eth_getTransactionByBlockNumberAndIndex_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getTransactionByBlockNumberAndIndex"
    },
    {
     "expr": "rate(rpc_duration_eth_getTransactionByHash_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getTransactionByHash"
    },
    {
     "expr": "rate(rpc_duration_eth_getTransactionCount_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getTransactionCount"
    },
    {
     "expr": "rate(rpc_duration_eth_getTransactionReceipt_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getTransactionReceipt"
    },
    {
     "expr": "rate(rpc_duration_eth_getUncleCountByBlockHash_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getUncleCountByBlockHash"
    },
    {
     "expr": "rate(rpc_duration_eth_getUncleCountByBlockNumber_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_getUncleCountByBlockNumber"
    },
    {
     "expr": "rate(rpc_duration_eth_mining_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_mining_success"
    },
    {
     "expr": "rate(rpc_duration_eth_newBlockFilter_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_newBlockFilter"
    },
    {
     "expr": "rate(rpc_duration_eth_newFilter_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_newFilter"
    },
    {
     "expr": "rate(rpc_duration_eth_newPendingTransactionFilter_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_newPendingTransactionFilter"
    },
    {
     "expr": "rate(rpc_duration_eth_sendRawTransaction_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_sendRawTransaction"
    },
    {
     "expr": "rate(rpc_duration_eth_signTransaction_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_signTransaction"
    },
    {
     "expr": "rate(rpc_duration_eth_subscribe_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_subscribe"
    },
    {
     "expr": "rate(rpc_duration_eth_syncing_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_syncing"
    },
    {
     "expr": "rate(rpc_duration_eth_unsubscribe_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "eth_unsubscribe"
    },
    {
     "expr": "rate(rpc_duration_statediff_writeStateDiffFor_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "statediff_writeStateDiffFor"
    },
    {
     "expr": "rate(rpc_duration_statediff_writeStateDiffAt_success_count{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "statediff_writeStateDiffAt"
    }
   ]
  },
  {
   "title": "Keycloak Logins/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(keycloak_logins{instance=\"keycloak:8080\"}[90s]) * 60",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Block Positions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{instance=\"${node}:6060\"}",
     "legendFormat": "geth"
    },
    {
     "expr": "statediff_service_last_statediff_height{instance=\"${node}:6060\"}",
     "legendFormat": "statediff"
    }
   ]
  },
  {
   "title": "Block Distance (geth to statediff)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "clamp_min(chain_head_block{instance=\"${node}:6060\"} - on() statediff_service_last_statediff_height{instance=\"${node}:6060\"}, 0)",
     "legendFormat": "Distance"
    }
   ]
  },
  {
   "title": "Statediff Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(statediff_service_succeeded{instance=\"${node}:6060\"}[1m])",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "increase(statediff_service_failed{instance=\"${node}:6060\"}[1m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "statediff_service_underway{instance=\"${node}:6060\"}",
     "legendFormat": "Underway"
    }
   ]
  },
  {
   "title": "Statediff Duty Cycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(statediff_service_total_processing_time{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statediff API Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(statediff_service_api_requests{instance=\"${node}:6060\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}