apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://monitoring-influxdb:8086
    database: agave_metrics
    user: admin
    isDefault: true
    editable: true
    secureJsonData:
      password: admin
    jsonData:
      timeInterval: 10s
      httpMode: GET
